DROP TABLE IF EXISTS balance_sheet;

CREATE TABLE balance_sheet (
    ID INT IDENTITY(1,1) NOT NULL,
    Date DATE NOT NULL,
    Ordinary_Shares_Number DECIMAL(20, 2),
    Share_Issued DECIMAL(20, 2),
    Net_Debt DECIMAL(20, 2),
    Total_Debt DECIMAL(20, 2),
    Tangible_Book_Value DECIMAL(20, 2),
    Invested_Capital DECIMAL(20, 2),
    Working_Capital DECIMAL(20, 2),
    Net_Tangible_Assets DECIMAL(20, 2),
    Common_Stock_Equity DECIMAL(20, 2),
    Total_Capitalization DECIMAL(20, 2),
    Total_Equity_Gross_Minority_Interest DECIMAL(20, 2),
    Stockholders_Equity DECIMAL(20, 2),
    Gains_Losses_Not_Affecting_Retained_Earnings DECIMAL(20, 2),
    Retained_Earnings DECIMAL(20, 2),
    Capital_Stock DECIMAL(20, 2),
    Common_Stock DECIMAL(20, 2),
    Total_Liabilities_Net_Minority_Interest DECIMAL(20, 2),
    Total_Non_Current_Liabilities_Net_Minority_Interest DECIMAL(20, 2),
    Other_Non_Current_Liabilities DECIMAL(20, 2),
    Tradeand_Other_Payables_Non_Current DECIMAL(20, 2),
    Long_Term_Debt_And_Capital_Lease_Obligation DECIMAL(20, 2),
    Long_Term_Debt DECIMAL(20, 2),
    Current_Liabilities DECIMAL(20, 2),
    Other_Current_Liabilities DECIMAL(20, 2),
    Current_Deferred_Liabilities DECIMAL(20, 2),
    Current_Deferred_Revenue DECIMAL(20, 2),
    Current_Debt_And_Capital_Lease_Obligation DECIMAL(20, 2),
    Current_Debt DECIMAL(20, 2),
    Other_Current_Borrowings DECIMAL(20, 2),
    Commercial_Paper DECIMAL(20, 2),
    Payables_And_Accrued_Expenses DECIMAL(20, 2),
    Payables DECIMAL(20, 2),
    Accounts_Payable DECIMAL(20, 2),
    Total_Assets DECIMAL(20, 2),
    Total_Non_Current_Assets DECIMAL(20, 2),
    Other_Non_Current_Assets DECIMAL(20, 2),
    Investments_And_Advances DECIMAL(20, 2),
    Other_Investments DECIMAL(20, 2),
    Investmentin_Financial_Assets DECIMAL(20, 2),
    Available_For_Sale_Securities DECIMAL(20, 2),
    Net_PPE DECIMAL(20, 2),
    Accumulated_Depreciation DECIMAL(20, 2),
    Gross_PPE DECIMAL(20, 2),
    Leases DECIMAL(20, 2),
    Machinery_Furniture_Equipment DECIMAL(20, 2),
    Land_And_Improvements DECIMAL(20, 2),
    Properties DECIMAL(20, 2),
    Current_Assets DECIMAL(20, 2),
    Other_Current_Assets DECIMAL(20, 2),
    Inventory DECIMAL(20, 2),
    Receivables DECIMAL(20, 2),
    Other_Receivables DECIMAL(20, 2),
    Accounts_Receivable DECIMAL(20, 2),
    Cash_Cash_Equivalents_And_Short_Term_Investments DECIMAL(20, 2),
    Other_Short_Term_Investments DECIMAL(20, 2),
    Cash_And_Cash_Equivalents DECIMAL(20, 2),
    Cash_Equivalents DECIMAL(20, 2),
    Cash_Financial DECIMAL(20, 2),
    PRIMARY KEY (ID, Date)
);


drop table if exists cash_flow_statement;
CREATE TABLE cash_flow_statement (
    ID INT IDENTITY(1,1) NOT NULL,
    Date DATE NOT NULL,
    Free_Cash_Flow DECIMAL(20, 2),
    Repurchase_Of_Capital_Stock DECIMAL(20, 2),
    Repayment_Of_Debt DECIMAL(20, 2),
    Issuance_Of_Debt DECIMAL(20, 2),
    Issuance_Of_Capital_Stock DECIMAL(20, 2),
    Capital_Expenditure DECIMAL(20, 2),
    Interest_Paid_Supplemental_Data DECIMAL(20, 2),
    Income_Tax_Paid_Supplemental_Data DECIMAL(20, 2),
    End_Cash_Position DECIMAL(20, 2),
    Beginning_Cash_Position DECIMAL(20, 2),
    Changes_In_Cash DECIMAL(20, 2),
    Financing_Cash_Flow DECIMAL(20, 2),
    Cash_Flow_From_Continuing_Financing_Activities DECIMAL(20, 2),
    Net_Other_Financing_Charges DECIMAL(20, 2),
    Cash_Dividends_Paid DECIMAL(20, 2),
    Common_Stock_Dividend_Paid DECIMAL(20, 2),
    Net_Common_Stock_Issuance DECIMAL(20, 2),
    Common_Stock_Payments DECIMAL(20, 2),
    Common_Stock_Issuance DECIMAL(20, 2),
    Net_Issuance_Payments_Of_Debt DECIMAL(20, 2),
    Net_Short_Term_Debt_Issuance DECIMAL(20, 2),
    Short_Term_Debt_Payments DECIMAL(20, 2),
    Short_Term_Debt_Issuance DECIMAL(20, 2),
    Net_Long_Term_Debt_Issuance DECIMAL(20, 2),
    Long_Term_Debt_Payments DECIMAL(20, 2),
    Long_Term_Debt_Issuance DECIMAL(20, 2),
    Investing_Cash_Flow DECIMAL(20, 2),
    Cash_Flow_From_Continuing_Investing_Activities DECIMAL(20, 2),
    Net_Other_Investing_Changes DECIMAL(20, 2),
    Net_Investment_Purchase_And_Sale DECIMAL(20, 2),
    Sale_Of_Investment DECIMAL(20, 2),
    Purchase_Of_Investment DECIMAL(20, 2),
    Net_Business_Purchase_And_Sale DECIMAL(20, 2),
    Purchase_Of_Business DECIMAL(20, 2),
    Net_PPE_Purchase_And_Sale DECIMAL(20, 2),
    Purchase_Of_PPE DECIMAL(20, 2),
    Operating_Cash_Flow DECIMAL(20, 2),
    Cash_Flow_From_Continuing_Operating_Activities DECIMAL(20, 2),
    Change_In_Working_Capital DECIMAL(20, 2),
    Change_In_Other_Working_Capital DECIMAL(20, 2),
    Change_In_Other_Current_Liabilities DECIMAL(20, 2),
    Change_In_Other_Current_Assets DECIMAL(20, 2),
    Change_In_Payables_And_Accrued_Expense DECIMAL(20, 2),
    Change_In_Payable DECIMAL(20, 2),
    Change_In_Account_Payable DECIMAL(20, 2),
    Change_In_Inventory DECIMAL(20, 2),
    Change_In_Receivables DECIMAL(20, 2),
    Changes_In_Account_Receivables DECIMAL(20, 2),
    Other_Non_Cash_Items DECIMAL(20, 2),
    Stock_Based_Compensation DECIMAL(20, 2),
    Deferred_Tax DECIMAL(20, 2),
    Deferred_Income_Tax DECIMAL(20, 2),
    Depreciation_Amortization_Depletion DECIMAL(20, 2),
    Depreciation_And_Amortization DECIMAL(20, 2),
    Net_Income_From_Continuing_Operations DECIMAL(20, 2),
    PRIMARY KEY (ID, Date)
);


drop table if exists income_statement;
CREATE TABLE income_statement (
    ID INT IDENTITY(1,1) NOT NULL,
    Date DATE NOT NULL,
    Tax_Effect_Of_Unusual_Items DECIMAL(20, 2),
    Tax_Rate_For_Calcs DECIMAL(20, 2),
    Normalized_EBITDA DECIMAL(20, 2),
    Net_Income_From_Continuing_Operation_Net_Minority_Interest DECIMAL(20, 2),
    Reconciled_Depreciation DECIMAL(20, 2),
    Reconciled_Cost_Of_Revenue DECIMAL(20, 2),
    EBITDA DECIMAL(20, 2),
    EBIT DECIMAL(20, 2),
    Net_Interest_Income DECIMAL(20, 2),
    Interest_Expense DECIMAL(20, 2),
    Interest_Income DECIMAL(20, 2),
    Normalized_Income DECIMAL(20, 2),
    Net_Income_From_Continuing_And_Discontinued_Operation DECIMAL(20, 2),
    Total_Expenses DECIMAL(20, 2),
    Total_Operating_Income_As_Reported DECIMAL(20, 2),
    Diluted_Average_Shares DECIMAL(20, 2),
    Basic_Average_Shares DECIMAL(20, 2),
    Diluted_EPS DECIMAL(20, 2),
    Basic_EPS DECIMAL(20, 2),
    Diluted_NI_Availto_Com_Stockholders DECIMAL(20, 2),
    Net_Income_Common_Stockholders DECIMAL(20, 2),
    Net_Income DECIMAL(20, 2),
    Net_Income_Including_Noncontrolling_Interests DECIMAL(20, 2),
    Net_Income_Continuous_Operations DECIMAL(20, 2),
    Tax_Provision DECIMAL(20, 2),
    Pretax_Income DECIMAL(20, 2),
    Other_Income_Expense DECIMAL(20, 2),
    Other_Non_Operating_Income_Expenses DECIMAL(20, 2),
    Net_Non_Operating_Interest_Income_Expense DECIMAL(20, 2),
    Interest_Expense_Non_Operating DECIMAL(20, 2),
    Interest_Income_Non_Operating DECIMAL(20, 2),
    Operating_Income DECIMAL(20, 2),
    Operating_Expense DECIMAL(20, 2),
    Research_And_Development DECIMAL(20, 2),
    Selling_General_And_Administration DECIMAL(20, 2),
    Gross_Profit DECIMAL(20, 2),
    Cost_Of_Revenue DECIMAL(20, 2),
    Total_Revenue DECIMAL(20, 2),
    Operating_Revenue DECIMAL(20, 2),
    PRIMARY KEY (ID, Date)
);
