
CREATE TABLE balance_sheet (
    ID INT IDENTITY(1,1) NOT NULL,
    Date DATE NOT NULL,
    Ordinary_Shares_Number DECIMAL(20, 2),
    Share_Issued DECIMAL(20, 2),
    Net_Debt DECIMAL(20, 2),
    Total_Debt DECIMAL(20, 2),
    Tangible_Book_Value DECIMAL(20, 2),
    Invested_Capital DECIMAL(20, 2),
    Working_Capital DECIMAL(20, 2),
    Net_Tangible_Assets DECIMAL(20, 2),
    Common_Stock_Equity DECIMAL(20, 2),
    Total_Capitalization DECIMAL(20, 2),
    Total_Equity_Gross_Minority_Interest DECIMAL(20, 2),
    Stockholders_Equity DECIMAL(20, 2),
    Gains_Losses_Not_Affecting_Retained_Earnings DECIMAL(20, 2),
    Retained_Earnings DECIMAL(20, 2),
    Capital_Stock DECIMAL(20, 2),
    Common_Stock DECIMAL(20, 2),
    Total_Liabilities_Net_Minority_Interest DECIMAL(20, 2),
    Total_Non_Current_Liabilities_Net_Minority_Interest DECIMAL(20, 2),
    Other_Non_Current_Liabilities DECIMAL(20, 2),
    Tradeand_Other_Payables_Non_Current DECIMAL(20, 2),
    Long_Term_Debt_And_Capital_Lease_Obligation DECIMAL(20, 2),
    Long_Term_Debt DECIMAL(20, 2),
    Current_Liabilities DECIMAL(20, 2),
    Other_Current_Liabilities DECIMAL(20, 2),
    Current_Deferred_Liabilities DECIMAL(20, 2),
    Current_Deferred_Revenue DECIMAL(20, 2),
    Current_Debt_And_Capital_Lease_Obligation DECIMAL(20, 2),
    Current_Debt DECIMAL(20, 2),
    Other_Current_Borrowings DECIMAL(20, 2),
    Commercial_Paper DECIMAL(20, 2),
    Payables_And_Accrued_Expenses DECIMAL(20, 2),
    Payables DECIMAL(20, 2),
    Accounts_Payable DECIMAL(20, 2),
    Total_Assets DECIMAL(20, 2),
    Total_Non_Current_Assets DECIMAL(20, 2),
    Other_Non_Current_Assets DECIMAL(20, 2),
    Investments_And_Advances DECIMAL(20, 2),
    Other_Investments DECIMAL(20, 2),
    Investmentin_Financial_Assets DECIMAL(20, 2),
    Available_For_Sale_Securities DECIMAL(20, 2),
    Net_PPE DECIMAL(20, 2),
    Accumulated_Depreciation DECIMAL(20, 2),
    Gross_PPE DECIMAL(20, 2),
    Leases DECIMAL(20, 2),
    Machinery_Furniture_Equipment DECIMAL(20, 2),
    Land_And_Improvements DECIMAL(20, 2),
    Properties DECIMAL(20, 2),
    Current_Assets DECIMAL(20, 2),
    Other_Current_Assets DECIMAL(20, 2),
    Inventory DECIMAL(20, 2),
    Receivables DECIMAL(20, 2),
    Other_Receivables DECIMAL(20, 2),
    Accounts_Receivable DECIMAL(20, 2),
    Cash_Cash_Equivalents_And_Short_Term_Investments DECIMAL(20, 2),
    Other_Short_Term_Investments DECIMAL(20, 2),
    Cash_And_Cash_Equivalents DECIMAL(20, 2),
    Cash_Equivalents DECIMAL(20, 2),
    Cash_Financial DECIMAL(20, 2),
    PRIMARY KEY (ID, Date)
);
