
CREATE TABLE cash_flow_statement (
    ID INT IDENTITY(1,1) NOT NULL,
    Date DATE NOT NULL,
    Free_Cash_Flow DECIMAL(20, 2),
    Repurchase_Of_Capital_Stock DECIMAL(20, 2),
    Repayment_Of_Debt DECIMAL(20, 2),
    Issuance_Of_Debt DECIMAL(20, 2),
    Issuance_Of_Capital_Stock DECIMAL(20, 2),
    Capital_Expenditure DECIMAL(20, 2),
    Interest_Paid_Supplemental_Data DECIMAL(20, 2),
    Income_Tax_Paid_Supplemental_Data DECIMAL(20, 2),
    End_Cash_Position DECIMAL(20, 2),
    Beginning_Cash_Position DECIMAL(20, 2),
    Changes_In_Cash DECIMAL(20, 2),
    Financing_Cash_Flow DECIMAL(20, 2),
    Cash_Flow_From_Continuing_Financing_Activities DECIMAL(20, 2),
    Net_Other_Financing_Charges DECIMAL(20, 2),
    Cash_Dividends_Paid DECIMAL(20, 2),
    Common_Stock_Dividend_Paid DECIMAL(20, 2),
    Net_Common_Stock_Issuance DECIMAL(20, 2),
    Common_Stock_Payments DECIMAL(20, 2),
    Common_Stock_Issuance DECIMAL(20, 2),
    Net_Issuance_Payments_Of_Debt DECIMAL(20, 2),
    Net_Short_Term_Debt_Issuance DECIMAL(20, 2),
    Short_Term_Debt_Payments DECIMAL(20, 2),
    Short_Term_Debt_Issuance DECIMAL(20, 2),
    Net_Long_Term_Debt_Issuance DECIMAL(20, 2),
    Long_Term_Debt_Payments DECIMAL(20, 2),
    Long_Term_Debt_Issuance DECIMAL(20, 2),
    Investing_Cash_Flow DECIMAL(20, 2),
    Cash_Flow_From_Continuing_Investing_Activities DECIMAL(20, 2),
    Net_Other_Investing_Changes DECIMAL(20, 2),
    Net_Investment_Purchase_And_Sale DECIMAL(20, 2),
    Sale_Of_Investment DECIMAL(20, 2),
    Purchase_Of_Investment DECIMAL(20, 2),
    Net_Business_Purchase_And_Sale DECIMAL(20, 2),
    Purchase_Of_Business DECIMAL(20, 2),
    Net_PPE_Purchase_And_Sale DECIMAL(20, 2),
    Purchase_Of_PPE DECIMAL(20, 2),
    Operating_Cash_Flow DECIMAL(20, 2),
    Cash_Flow_From_Continuing_Operating_Activities DECIMAL(20, 2),
    Change_In_Working_Capital DECIMAL(20, 2),
    Change_In_Other_Working_Capital DECIMAL(20, 2),
    Change_In_Other_Current_Liabilities DECIMAL(20, 2),
    Change_In_Other_Current_Assets DECIMAL(20, 2),
    Change_In_Payables_And_Accrued_Expense DECIMAL(20, 2),
    Change_In_Payable DECIMAL(20, 2),
    Change_In_Account_Payable DECIMAL(20, 2),
    Change_In_Inventory DECIMAL(20, 2),
    Change_In_Receivables DECIMAL(20, 2),
    Changes_In_Account_Receivables DECIMAL(20, 2),
    Other_Non_Cash_Items DECIMAL(20, 2),
    Stock_Based_Compensation DECIMAL(20, 2),
    Deferred_Tax DECIMAL(20, 2),
    Deferred_Income_Tax DECIMAL(20, 2),
    Depreciation_Amortization_Depletion DECIMAL(20, 2),
    Depreciation_And_Amortization DECIMAL(20, 2),
    Net_Income_From_Continuing_Operations DECIMAL(20, 2),
    PRIMARY KEY (ID, Date)
);
