
CREATE TABLE income_statement (
    ID INT IDENTITY(1,1) NOT NULL,
    Date DATE NOT NULL,
    Tax_Effect_Of_Unusual_Items DECIMAL(20, 2),
    Tax_Rate_For_Calcs DECIMAL(20, 2),
    Normalized_EBITDA DECIMAL(20, 2),
    Net_Income_From_Continuing_Operation_Net_Minority_Interest DECIMAL(20, 2),
    Reconciled_Depreciation DECIMAL(20, 2),
    Reconciled_Cost_Of_Revenue DECIMAL(20, 2),
    EBITDA DECIMAL(20, 2),
    EBIT DECIMAL(20, 2),
    Net_Interest_Income DECIMAL(20, 2),
    Interest_Expense DECIMAL(20, 2),
    Interest_Income DECIMAL(20, 2),
    Normalized_Income DECIMAL(20, 2),
    Net_Income_From_Continuing_And_Discontinued_Operation DECIMAL(20, 2),
    Total_Expenses DECIMAL(20, 2),
    Total_Operating_Income_As_Reported DECIMAL(20, 2),
    Diluted_Average_Shares DECIMAL(20, 2),
    Basic_Average_Shares DECIMAL(20, 2),
    Diluted_EPS DECIMAL(20, 2),
    Basic_EPS DECIMAL(20, 2),
    Diluted_NI_Availto_Com_Stockholders DECIMAL(20, 2),
    Net_Income_Common_Stockholders DECIMAL(20, 2),
    Net_Income DECIMAL(20, 2),
    Net_Income_Including_Noncontrolling_Interests DECIMAL(20, 2),
    Net_Income_Continuous_Operations DECIMAL(20, 2),
    Tax_Provision DECIMAL(20, 2),
    Pretax_Income DECIMAL(20, 2),
    Other_Income_Expense DECIMAL(20, 2),
    Other_Non_Operating_Income_Expenses DECIMAL(20, 2),
    Net_Non_Operating_Interest_Income_Expense DECIMAL(20, 2),
    Interest_Expense_Non_Operating DECIMAL(20, 2),
    Interest_Income_Non_Operating DECIMAL(20, 2),
    Operating_Income DECIMAL(20, 2),
    Operating_Expense DECIMAL(20, 2),
    Research_And_Development DECIMAL(20, 2),
    Selling_General_And_Administration DECIMAL(20, 2),
    Gross_Profit DECIMAL(20, 2),
    Cost_Of_Revenue DECIMAL(20, 2),
    Total_Revenue DECIMAL(20, 2),
    Operating_Revenue DECIMAL(20, 2),
    PRIMARY KEY (ID, Date)
);
